# Generated by Django 5.2.11 on 2026-02-04 03:50

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDrawerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_balance', models.PositiveIntegerField(help_text='Opening balance in XOF')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_balance', models.PositiveIntegerField(blank=True, help_text='Actual closing balance in XOF', null=True)),
                ('expected_balance', models.PositiveIntegerField(blank=True, help_text='Expected closing balance based on transactions', null=True)),
                ('variance', models.IntegerField(blank=True, help_text='Difference between actual and expected (can be negative)', null=True)),
                ('variance_notes', models.TextField(blank=True, help_text='Notes explaining any variance')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_drawer_sessions', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(help_text='Provider identifier: wave, orange, mtn, cash', max_length=20)),
                ('name', models.CharField(help_text='Display name for the payment method', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-specific configuration (NOT secrets)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display payment methods')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('business', 'provider_code')},
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(help_text='Payment amount in XOF (integer)')),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('expired', 'Expired')], default='pending', max_length=50, protected=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key to prevent duplicate payments', max_length=255, unique=True)),
                ('provider_code', models.CharField(help_text='Provider that processed this payment', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text='Reference from the payment provider', max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Raw response from the provider')),
                ('error_code', models.CharField(blank=True, help_text='Error code if payment failed', max_length=100)),
                ('error_message', models.TextField(blank=True, help_text='Error message if payment failed')),
                ('refunded_amount', models.PositiveIntegerField(default=0, help_text='Amount refunded in XOF')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod')),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='payments_pa_busines_c8c99d_idx'), models.Index(fields=['provider_reference'], name='payments_pa_provide_48cfd7_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
