# Generated by Django 5.2.11 on 2026-02-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_busines_0cb2e2_idx',
            old_name='payments_pa_busines_c8c99d_idx',
        ),
    ]
