# Generated by Django 5.2.11 on 2026-02-03 21:52

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, help_text='Optional SKU code', max_length=50)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Litre'), ('mL', 'Millilitre'), ('piece', 'Piece'), ('portion', 'Portion'), ('other', 'Other')], default='piece', max_length=20)),
                ('current_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Current quantity in stock', max_digits=10)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=4, help_text='Alert when stock falls below this level', max_digits=10, null=True)),
                ('low_stock_alert_sent', models.BooleanField(default=False, help_text='Prevents duplicate alerts')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentication.business')),
            ],
            options={
                'verbose_name': 'historical stock item',
                'verbose_name_plural': 'historical stock items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, help_text='Optional SKU code', max_length=50)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Litre'), ('mL', 'Millilitre'), ('piece', 'Piece'), ('portion', 'Portion'), ('other', 'Other')], default='piece', max_length=20)),
                ('current_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Current quantity in stock', max_digits=10)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=4, help_text='Alert when stock falls below this level', max_digits=10, null=True)),
                ('low_stock_alert_sent', models.BooleanField(default=False, help_text='Prevents duplicate alerts')),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_change', models.DecimalField(decimal_places=4, help_text='Positive for stock in, negative for stock out', max_digits=10)),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment')], max_length=20)),
                ('reason', models.CharField(choices=[('purchase', 'Purchase'), ('order_usage', 'Order Usage'), ('waste', 'Waste'), ('theft', 'Theft'), ('correction', 'Correction'), ('transfer', 'Transfer'), ('initial', 'Initial Stock')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reference_type', models.CharField(blank=True, help_text="Type of reference (e.g., 'Order')", max_length=50)),
                ('reference_id', models.UUIDField(blank=True, help_text='Reference object ID', null=True)),
                ('balance_after', models.DecimalField(decimal_places=4, help_text='Stock balance after this movement', max_digits=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('current_quantity__gte', 0)), name='stock_item_non_negative_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('business', 'sku'), name='unique_business_sku'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', '-created_at'], name='inventory_s_stock_i_73796c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['business', '-created_at'], name='inventory_s_busines_6b5a95_idx'),
        ),
    ]
