# Generated by Django 5.2.11 on 2026-02-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_biz360_transformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name'], 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='show_branding',
            field=models.BooleanField(default=True, help_text='Show BIZ360 branding on free tier'),
        ),
    ]
