# Generated by Django 5.2.11 on 2026-02-03 21:17

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('menu', '0002_alter_category_managers_alter_menuitem_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.PositiveIntegerField(help_text='Daily order number (resets each day per restaurant)')),
                ('order_date', models.DateField(help_text='Date of the order (for daily sequence uniqueness)', null=True)),
                ('order_type', models.CharField(choices=[('dine_in', 'Dine In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='dine_in', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.PositiveIntegerField(default=0, help_text='Subtotal in XOF before any discounts')),
                ('discount', models.PositiveIntegerField(default=0, help_text='Discount amount in XOF')),
                ('total', models.PositiveIntegerField(default=0, help_text='Final total in XOF (subtotal - discount)')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Copied from menu item at order time for historical accuracy', max_length=200)),
                ('unit_price', models.PositiveIntegerField(help_text='Price in XOF at order time')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('modifiers_total', models.IntegerField(default=0, help_text='Sum of modifier price adjustments (can be negative)')),
                ('line_total', models.PositiveIntegerField(default=0, help_text='(unit_price + modifiers_total) * quantity')),
                ('notes', models.TextField(blank=True)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
            ],
            options={
                'ordering': ['created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Copied from modifier option at order time', max_length=100)),
                ('price_adjustment', models.IntegerField(default=0, help_text='Price adjustment in XOF (can be negative)')),
                ('modifier_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_modifiers', to='menu.modifieroption')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.orderitem')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
            ],
            options={
                'ordering': ['created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('business', 'number')},
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Required for dine-in orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.table'),
        ),
        migrations.CreateModel(
            name='DailySequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sequences', to='authentication.business')),
            ],
            options={
                'unique_together': {('business', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'status'], name='orders_orde_busines_17016b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'created_at'], name='orders_orde_busines_763bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('business', 'order_number', 'order_date')},
        ),
    ]
