# Generated by Django 5.2.11 on 2026-02-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_invoice_tax_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_busines_1a89b8_idx',
            old_name='orders_orde_busines_17016b_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_busines_754e0c_idx',
            old_name='orders_orde_busines_763bf4_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_invoice_1f27b8_idx',
            old_name='orders_orde_invoice_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_dgi_sub_9e316f_idx',
            old_name='orders_orde_dgi_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(help_text='Daily order number (resets each day per business)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery'), ('in_store', 'In Store'), ('online', 'Online')], default='dine_in', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveIntegerField(default=0, help_text='Subtotal in XOF before discounts and tax'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, help_text='Final total in XOF (TTC - including tax)'),
        ),
    ]
