# Generated by Django 5.2.11 on 2026-02-04 09:45

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_restaurant_plan_type_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenuStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('qr_scans', models.PositiveIntegerField(default=0)),
                ('top_items', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='List of most viewed item IDs (if item-level tracking added)', size=None)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Daily menu stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['restaurant', 'date'], name='analytics_d_restaur_bce2f9_idx')],
                'unique_together': {('restaurant', 'date')},
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MenuView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(help_text='Client-generated session ID for unique visitor tracking', max_length=100)),
                ('source', models.CharField(choices=[('qr', 'QR Code'), ('link', 'Direct Link'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='link', help_text='How the customer accessed the menu', max_length=20)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device user agent string', max_length=500)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.restaurant')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['restaurant', 'viewed_at'], name='analytics_m_restaur_781889_idx'), models.Index(fields=['restaurant', 'session_id'], name='analytics_m_restaur_9c1a9d_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
