# Generated by Django 5.2.11 on 2026-02-05 07:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_alter_business_options_alter_business_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_advance_hours', models.PositiveIntegerField(default=1, help_text='Minimum hours in advance a reservation can be made')),
                ('max_advance_days', models.PositiveIntegerField(default=30, help_text='Maximum days in advance a reservation can be made')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration of each booking time slot')),
                ('default_dining_duration_minutes', models.PositiveIntegerField(default=90, help_text='Default dining duration for table turnover')),
                ('max_party_size', models.PositiveIntegerField(default=10, help_text='Maximum party size for online booking')),
                ('require_phone', models.BooleanField(default=True, help_text='Require phone number for booking')),
                ('require_email', models.BooleanField(default=False, help_text='Require email for booking')),
                ('confirmation_required', models.BooleanField(default=False, help_text='Require business confirmation before booking is active')),
                ('cancellation_hours', models.PositiveIntegerField(default=2, help_text='Hours before reservation that cancellation is allowed')),
                ('no_show_threshold', models.PositiveIntegerField(default=3, help_text='Number of no-shows before customer is flagged')),
                ('confirmation_message', models.TextField(blank=True, help_text='Custom message to include in booking confirmation')),
                ('reminder_hours', models.PositiveIntegerField(default=24, help_text='Hours before reservation to send reminder')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
            ],
            options={
                'verbose_name': 'Reservation Settings',
                'verbose_name_plural': 'Reservation Settings',
            },
        ),
        migrations.CreateModel(
            name='TableConfiguration',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Table identifier (e.g., 'Table 1', 'Booth A')", max_length=50)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of guests')),
                ('min_capacity', models.PositiveIntegerField(default=1, help_text='Minimum number of guests')),
                ('location', models.CharField(blank=True, help_text="Location in business (e.g., 'Indoor', 'Terrace', 'Private Room')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=90)),
                ('party_size', models.PositiveIntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('online', 'Online Booking'), ('phone', 'Phone'), ('walk_in', 'Walk-in'), ('third_party', 'Third Party')], default='online', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('occasion', models.CharField(blank=True, help_text='Birthday, Anniversary, Business, etc.', max_length=50)),
                ('confirmation_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.tableconfiguration')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('party_size', models.PositiveIntegerField()),
                ('is_notified', models.BooleanField(default=False)),
                ('is_seated', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('estimated_wait_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entry', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_open', models.BooleanField(default=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('last_seating_time', models.TimeField(blank=True, help_text='Last time reservations are accepted', null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
            ],
            options={
                'verbose_name': 'Business Hours',
                'verbose_name_plural': 'Business Hours',
                'ordering': ['day_of_week', 'open_time'],
                'unique_together': {('business', 'day_of_week', 'open_time')},
            },
        ),
        migrations.CreateModel(
            name='SpecialHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('is_closed', models.BooleanField(default=False, help_text='Restaurant closed this day')),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for special hours', max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='authentication.business')),
            ],
            options={
                'verbose_name': 'Special Hours',
                'verbose_name_plural': 'Special Hours',
                'ordering': ['date'],
                'unique_together': {('business', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['business', 'date', 'status'], name='reservation_busines_70cbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['confirmation_code'], name='reservation_confirm_3c8353_idx'),
        ),
    ]
